# Vizier

In [18]:
from astropop.catalogs import vizier
from astropy.time import Time

In [6]:
cat = vizier.ucac4('HD 674', '10 arcmin')

2023-01-11 09:02:12,349 astropop - INFO - Quering region centered at <SkyCoord (ICRS): (ra, dec) in deg
    (2.71676125, -54.29064972)> with radius 10arcmin  [_sources_catalog]


In [7]:
cat.available_filters

['J', 'H', 'K', 'B', 'V', 'g', 'r', 'i']

In [8]:
cat.table()

<Table length=42>
       id                ra             dec         pm_ra_cosdec           pm_dec               J          ... g_error         r          r_error         i          i_error
                        deg             deg           mas / yr            mas / yr                         ...                                                              
     str16            float64         float64         float64             float64            float64       ... float64      float64       float64      float64       float64
---------------- ------------------ ----------- ------------------- ------------------- ------------------ ... ------- ------------------ ------- ------------------ -------
UCAC4 179-000175 2.7167508999999996 -54.2906592                 2.1                 7.0 10.156999588012695 ...     nan                nan     nan 10.687999725341797    0.01
UCAC4 179-000177          2.7463127 -54.2873887                -8.2  0.2999999999999999  13.79699993133545 ...    0.01 15.329000473022461    0.01  14.92300033569336    0.01
UCAC4 179-000176           2.722068  -54.265292                15.3 -57.900000000000006 15.307000160217285 ...     nan                nan     nan                nan     nan
             ...                ...         ...                 ...                 ...                ... ...     ...                ...     ...                ...     ...
UCAC4 179-000189          2.9935983 -54.2751984 -141.79999999999998               -23.9 15.654000282287598 ...     nan                nan     nan                nan     nan
UCAC4 179-000188 2.9608708999999993 -54.2099495  -42.10000000000001               -42.5 6.2769999504089355 ...    0.01  9.086999893188477    0.01  8.043999671936035    0.06
UCAC4 178-000197          2.7849948 -54.4497548                16.0  -7.099999999999999 14.812999725341797 ...    0.01 15.991000175476074    0.01                nan     nan
UCAC4 178-000183          2.5374603 -54.4175698                21.3  -6.599999999999998 12.322999954223633 ...    0.03 13.467000007629395     0.0  13.26099967956543    0.01

In [10]:
cat_matched = cat.match_objects(ra=[2.7167509, 2.722068, 2.7849948],
                                dec=[-54.2906592, -54.265292, -54.4497548], '1 arcsec')

In [11]:
cat_matched.table()

<Table length=3>
       id                ra             dec     pm_ra_cosdec       pm_dec               J          ...        g         g_error         r          r_error         i          i_error
                        deg             deg       mas / yr        mas / yr                         ...                                                                               
     str16            float64         float64     float64         float64            float64       ...     float64      float64      float64       float64      float64       float64
---------------- ------------------ ----------- ------------ ------------------ ------------------ ... ---------------- ------- ------------------ ------- ------------------ -------
UCAC4 179-000175 2.7167508999999996 -54.2906592          2.1                7.0 10.156999588012695 ...              nan     nan                nan     nan 10.687999725341797    0.01
UCAC4 179-000176           2.722068  -54.265292         15.3 -57.90000000000002 15.307000160217285 ...              nan     nan                nan     nan                nan     nan
UCAC4 178-000197          2.7849948 -54.4497548         16.0 -7.099999999999998 14.812999725341797 ... 16.6560001373291    0.01 15.991000175476074    0.01                nan     nan

In [14]:
cat_matched.magnitude('B')

<QFloat
array([10.75+-0.01, nan+-nan, 17.05+-0.06], dtype=object)
unit=mag>

In [22]:
cat_matched.mag_list('B')

array([[1.07519999e+01, 1.00000000e-02],
       [           nan,            nan],
       [1.70470009e+01, 6.00000000e-02]])

In [15]:
cat_matched.skycoord()

<SkyCoord (ICRS): (ra, dec) in deg
    [(2.7167509, -54.2906592), (2.722068 , -54.265292 ),
     (2.7849948, -54.4497548)]
 (pm_ra_cosdec, pm_dec) in mas / yr
    [( 2.1,   7. ), (15.3, -57.9), (16. ,  -7.1)]>

# Simbad

In [23]:
from astropop.catalogs import simbad

In [31]:
simbad.simbad_query_id(101.28715, -16.7161158, '10 arcsec')

array('alf CMa', dtype='<U7')

In [28]:
simbad.simbad_query_id(101.28715, -16.7161158, '10 arcsec', name_order=['HD', 'HR', 'HYP', 'TYC', 'AAVSO'])

array('HD 48915', dtype='<U8')

In [35]:
cat = simbad.SimbadSourcesCatalog('Sirius', '10 arcmin', band=['B', 'V', 'g', 'r', 'i', 'z'])

2023-01-11 09:38:39,328 astropop - INFO - Quering region centered at <SkyCoord (ICRS): (ra, dec) in deg
    (101.287155, -16.71611583)> with radius 10arcmin  [_sources_catalog]


In [36]:
cat.table()

<Table length=197>
             id                      ra                 dec              pm_ra_cosdec             pm_dec          B    B_error ...    r    r_error    i    i_error    z    z_error
                                    deg                 deg                mas / yr              mas / yr                      ...                                                
           str28                  float64             float64              float64               float64       float32 float32 ... float32 float32 float32 float32 float32 float32
---------------------------- ------------------ ------------------- ---------------------- ------------------- ------- ------- ... ------- ------- ------- ------- ------- -------
                   * alf CMa         101.287155 -16.716115833333333                -546.01 -1223.0699999999997   -1.46     nan ...     nan     nan     nan     nan     nan     nan
                 * alf CMa B 101.28876708333333 -16.716867777777775               -461.571  -914.5200000000002    8.41     nan ...     nan     nan     nan     nan     nan     nan
[TSA98] J064510.77-164237.51 101.29487499999999 -16.710416666666667                    nan                 nan     nan     nan ...     nan     nan     nan     nan     nan     nan
                         ...                ...                 ...                    ...                 ...     ...     ... ...     ...     ...     ...     ...     ...     ...
Gaia DR3 2947052047079756544 101.45559458333332 -16.751795555555557    0.03799999999999999  1.2480000000000002     nan     nan ...     nan     nan     nan     nan     nan     nan
Gaia DR3 2947059812380376960 101.36422041666665 -16.567816666666666    0.12400000000000003               0.955     nan     nan ...     nan     nan     nan     nan     nan     nan
     2MASS J06454977-1644464          101.45743  -16.74625888888889   -0.07600000000000001  1.3470000000000002     nan     nan ...     nan     nan     nan     nan     nan     nan
Gaia DR3 2947055379974326016       101.44765875 -16.652292777777777 -0.0030000000000000027               1.255     nan     nan ...     nan     nan     nan     nan     nan     nan

In [37]:
cat.magnitude('V')

/home/julio/.anaconda/envs/astropop/lib/python3.11/site-packages/astropop/math/physical.py:130: RuntimeWarning: invalid value encountered in cast
  first_digit = -np.int_(np.floor(np.log10(np.abs(self._s))))
/home/julio/.anaconda/envs/astropop/lib/python3.11/site-packages/astropop/math/physical.py:130: RuntimeWarning: overflow encountered in scalar negative
  first_digit = -np.int_(np.floor(np.log10(np.abs(self._s))))


<QFloat
array([-1.4600000381469727+-nan, 8.4399995803833+-nan, nan+-nan, nan+-nan,
       nan+-nan, nan+-nan, nan+-nan, nan+-nan, nan+-nan,
       16.399999618530273+-nan, 14.5+-nan, 17.600000381469727+-nan,
       nan+-nan, 17.200000762939453+-nan, nan+-nan, nan+-nan,
       14.199999809265137+-nan, 17.899999618530273+-nan, nan+-nan,
       nan+-nan, 16.600000381469727+-nan, nan+-nan, nan+-nan,
       17.799999237060547+-nan, nan+-nan, nan+-nan,
       16.799999237060547+-nan, nan+-nan, nan+-nan, nan+-nan, nan+-nan,
       nan+-nan, nan+-nan, nan+-nan, nan+-nan, nan+-nan, nan+-nan,
       nan+-nan, nan+-nan, nan+-nan, nan+-nan, nan+-nan, nan+-nan,
       nan+-nan, nan+-nan, nan+-nan, nan+-nan, nan+-nan, nan+-nan,
       nan+-nan, nan+-nan, nan+-nan, nan+-nan, nan+-nan, nan+-nan,
       nan+-nan, nan+-nan, nan+-nan, nan+-nan, nan+-nan, nan+-nan,
       nan+-nan, nan+-nan, nan+-nan, nan+-nan, nan+-nan, nan+-nan,
       nan+-nan, nan+-nan, nan+-nan, nan+-nan, 8.45+-0.01, nan+-nan,
      

In [38]:
cat.magnitudes_bibcode('V')

array(['2002yCat.2237....0D', '', '', '', '', '', '', '', '', '', '', '',
       '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '',
       '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '',
       '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '',
       '', '', '', '', '', '', '', '', '2000A&A...355L..27H', '', '', '',
       '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '',
       '', '', '', '', '', '', '', '', '', '', '', '', '', '',
       '2012yCat.1322....0Z', '2000A&A...355L..27H', '', '', '', '', '',
       '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '',
       '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '',
       '', '', '', '', '2000A&A...355L..27H', '2000A&A...355L..27H', '',
       '', '', '', '', '', '', '', '', '', '', '', '',
       '2000A&A...355L..27H', '', '', '', '', '', '', '', '', '', '',
       '2000A&A...355L..27H', '', '', '2000A&A...355L..27H', '', '',

In [40]:
simbad.simbad_query_id(cat.skycoord().ra.degree, cat.skycoord().dec.degree, '1 arcsec')

array(['alf CMa', 'alf CMa B', '[TSA98] J064510.77-164237.51',
       '[TSA98] J064511.57-164240.56', '[TSA98] J064511.97-164240.59',
       '[BCL2000] 7', '[TSA98] J064510.48-164203.49', '[BCL2000] 3',
       '[TSA98] J064511.08-164205.53', '[BG91] 3', '[BG91] 2', '[BG91] 7',
       '[BCL2000] 4', '[BG91] 4', '[BCL2000] 2', '[BCL2000] 20',
       '[BG91] 1', '[BG91] 8', '[BCL2000] 18', '[BCL2000] 1', '[BG91] 5',
       '[BCL2000] 12', '[BCL2000] 8', '[BG91] 9', '[BCL2000] 13',
       '[BCL2000] 10', '[BG91] 6', '[BCL2000] 5', '[BCL2000] 11',
       '[BCL2000] 17', '[BCL2000] 31', '[BCL2000] 9', '[BCL2000] 6',
       '[BCL2000] 19', '[BCL2000] 25', '[BCL2000] 14', '[BCL2000] 32',
       '[BCL2000] 16', '[BCL2000] 28', 'Gaia DR3 2947056513845762688',
       '[BCL2000] 21', '[BCL2000] 22', '[BCL2000] 24', '[BCL2000] 26',
       '[BCL2000] 15', 'Gaia DR3 2947057338479481600', '[BCL2000] 23',
       'Gaia DR3 2947050088574534912', '[BCL2000] 29', '[BCL2000] 27',
       'Gaia DR3 2947056616